POST http://localhost:8090/api/v1/notes/deleteMultipleNotes?userId=14399290-7133-4aba-a14a-40a1a840250f
Content-Type: application/json

{
    "noteIds": [
        "d1a3cbcf-9cb4-4314-a493-66f44256c6ef"
    ]
}